[32mINFO    [0m root:test_userprofile.py:71 Testing SignUp
[32mINFO    [0m root:test_userprofile.py:73 Opening the signup page
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3E712EAD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8574c65d61e95db7758727a8d65fa307/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3E712EFD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8574c65d61e95db7758727a8d65fa307/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3E71B4510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8574c65d61e95db7758727a8d65fa307/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3E6CB7D10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8574c65d61e95db7758727a8d65fa307
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3E71C5E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8574c65d61e95db7758727a8d65fa307
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F3E71C6250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/8574c65d61e95db7758727a8d65fa307